[package]
name = "crap"
version = "0.2.1"
edition = "2021"
repository = "https://github.com/JustJam-Dev/CRApp"

[dependencies]
eframe = "0.29"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "macros", "chrono", "migrate"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
image = "0.24"
tiktoken-rs = "0.5"
egui_extras = { version = "0.29", features = ["image", "all_loaders"] }
rfd = "0.17.1"
base64 = "0.21"
png = "0.17"
arboard = "3.4"
rusqlite = { version = "0.32", features = ["bundled"] }
url = "2.5.8"
uuid = { version = "1.0", features = ["v4"] }
zspell = "0.5"
zip = "0.6"
walkdir = "2"
self_update = { version = "0.41", features = ["archive-zip", "compression-zip-deflate"] }
imageproc = "0.23.0"
rusttype = "0.9"
html-escape = "0.2"
